title: Prosper Atanley # your name (or website title) here
logo: "/images/LinkedIn- Pros.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Results-oriented Chartered Accountant with over seven years of experience in financial analysis, reporting, budgeting, and strategic planning. An adaptable and customer-focused financial leader with expertise in account reconciliations, cash management, and company record maintenance.
  <br><br>
  Won 2022 Halifax Innovation Challenge: sponsored by RBC and IBM
  <a href="https://innovationchallenge.agendamanagers.ca/">Read more</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/patanley/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
